pyrra-dev/pyrra

- Makefile
- cmd/api/main.go
As observed on MacOS, the command `make` was failing due to a problem in the Makefile and the corresponding reference of said folder in main.go.
This adjusts both the copy inside the Makefile and the reference in main.go.
Before:
```
rm -rf ./cmd/api/ui/build && cp -r ./ui/build/ ./cmd/api/ui/
go fmt ./...
go vet ./...
cmd/api/main.go:32:12: pattern ui/build: no matching files found
make: *** [Makefile:66: vet] Error 1
```
After:
```
rm -rf ./cmd/api/ui/build && cp -r ./ui/build ./cmd/api/ui/
go fmt ./...
go vet ./...
go build -o bin/api ./cmd/api/main.go
/Users/rrackow/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=pyrra-kubernetes webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/Users/rrackow/go/bin/controller-gen …
```
> Makefile,cmd/api/main.go: fix folder import path

- Makefile
- cmd/api/Dockerfile
- cmd/kubernetes/Dockerfile
List of changes:
- Use `${PWD}` instead of shelling out with `$(shell pwd)` in Makefile
- Use common make targets like `lint`, `build`, `clean`
- Add `clean` target to remove installed and built assets. This one may be improved later on.
- split building UI into multiple targets based on directories they provide (`ui/build`, `ui/node_modules`)
- Remove recursive removal where not necessary in Makefile
- Refactor both Dockerfiles to use provided Makefile and allow building UI in a container. This should allow specifying build directives only once in Makefile instead of duplicating it in multiple places.
- Unify Dockerfiles by copying the whole codebase into an intermediary build container.
Signed-off-by: paulfantom <pawel@krupa.net.pl>
> Makefile improvements and multi-stage container builds

- Makefile
- config/crd/bases/pyrra.dev_servicelevelobjectives.yaml
Signed-off-by: yeya24 <yb532204897@gmail.com>
`controller-gen` version is a little bit out of date and I can see the warning below when applying CRD to my local k8s cluster.
```
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```
> bump controller-gen tool version to latest

- ui/src/pages/Detail.tsx
Spinner is now shown when still loading status. 
Closes #15
> ui: Show spinner for loading Availabiltiy & Error Budget

- config/crd/bases/pyrra.dev_servicelevelobjectives.yaml
- kubernetes/api/v1alpha1/servicelevelobjective_types.go
Allow users to type "kubectl get slo" etc:
$ kubectl apply -f examples/pyrra-http-errors.yaml
servicelevelobjective.pyrra.dev/pyrra-api-errors created
$ kubectl get slo -n monitoring
NAME               AGE
pyrra-api-errors   5s
> Add SLO as shortname for kubernetes

- kubernetes/controllers/servicelevelobjective.go
- kubernetes/controllers/servicelevelobjective_test.go
By setting owner references on the object we create, kubernetes will
handle deletion of the generated PrometheusRule when the corresponding
ServiceLevelObjective is deleted.
Example:
k apply -f examples/pyrra-http-errors.yaml
servicelevelobjective.pyrra.dev/pyrra-api-errors created
we see that the controller generates a prometheusrule object:
k get prometheusrule,servicelevelobjective -n monitoring
NAME                                                    AGE
prometheusrule.monitoring.coreos.com/pyrra-api-errors   1s
servicelevelobjective.pyrra.dev/pyrra-api-errors        1s
when we delete the SLO, the matching rule is deleted:
k delete servicelevelobjective.pyrra.dev/pyrra-api-errors -n monitoring
k get prometheusrule,servicelevelobjective -n monitoring
No resources found in monitoring …
> Delete generated PrometheusRule by setting OwnerReferences

- main.go
- openapi/internal.go
This caused the Alerting Table to sometimes query the incorrect SLO alerts... 
While the query should be something like
```
ALERTS{slo="lastfm-api-errors",short="30m",long="6h"}
```
the SLO name wasn't properly populated and was instead
```
ALERTS{slo="",short="30m",long="6h"}
```
On my cluster it showed firing for another KubeAPIServer SLO although it was the wrong one...
> Add labels to internal SLO representation

- slo/promql_test.go
- slo/rules.go
- slo/rules_test.go
Especially having SLOs with matchers like `handler=~"/api.*"`.
> Improve rules generating for SLOs with regex matchers

- ui/src/components/graphs/ErrorBudgetGraph.tsx
- ui/src/components/graphs/ErrorsGraph.tsx
- ui/src/components/graphs/RequestsGraph.tsx
- ui/src/pages/Detail.tsx
The uplot graphs had hardcoded width of 1000px and twice 500px. Thus adding a window resize listener to automatically set the uplot's canvas to the outer container's width.
> ui: Make uplot graphs responsive with window resize listener

- ui/src/components/graphs/ErrorsGraph.tsx
Now we'll actually see 1% instead of 0.01% and so on. Something seemed off and it was...
Tests would be amazing for this!
> Fix ErrorsGraph by actually using mapped values

- main.go
- ui/public/index.html
- ui/src/App.tsx
- ui/src/components/AlertsTable.tsx
- ui/src/pages/Detail.tsx
- ui/src/pages/List.tsx
This is mostly needed for running the local instance npm dev server on localhost:3000 but still being able to talk to the API on localhost:9099.
> Make API_BASEPATH configurable based on PATH_PREFIX

- filesystem.go
- kubernetes/controllers/servicelevelobjective.go
- kubernetes/controllers/servicelevelobjective_test.go
- slo/rules.go
- slo/rules_test.go
This should especially make a difference on Prometheus CPU load.
Rather than evaluating these `increase(...[4w])` every 30s we relax this interval depending on how long the SLO's time window is, such that within e.g. 2m over the 4w not toooo much will change.
> Separate increase rules into separate rule group with higher interval

- Makefile
- config/crd/bases/pyrra.dev_servicelevelobjectives.json
- config/crd/bases/pyrra.dev_servicelevelobjectives.yaml
- kubernetes/api/v1alpha1/servicelevelobjective_types.go
- kubernetes/controllers/servicelevelobjective_test.go
- kubernetes_test.go
Add a gojsontoyaml converted for converting the YAML CRD to JSON and thus it's easier to be consumed in jsonnet.
The type change in the CRD from `model.Duration` to `string` was logical, as I've always overwritten the changes after generation... No CRD needs updating because of this.
> config/crd/bases: Generate YAML and JSON CRD files

- ui/src/components/graphs/ErrorsGraph.tsx
- ui/src/components/graphs/RequestsGraph.tsx
- ui/src/pages/Detail.scss
Some components were slightly offset and not centered anymore. This fixes that.
> ui: Fix paddings of components after bootstrap update

- main.go
This should improve things a lot more. Better for query range requests over weeks and better for instant query requests with `ALERTS` for example that will only be cached for up to 5s now.
> Improve caching by passing cache duration via context

- .github/workflows/container.yaml
In the hopes that if we have a branch in this repository we'll still get docker images that can be tried. However, exclude PRs that are coming from outside forks as they might be potentially harmful and we don't want to push them to our registry just like that.
> CI: Push docker image only if same repository

- .github/workflows/golangci-lint.yml
- slo/rules.go
- slo/rules_test.go
- slo/slo.go
This should fix golangci-lint again so that we can rebase all dependabot PRs and merge them in.
> Expose the Window struct

- README.md
- kubernetes/api/v1alpha1/servicelevelobjective_types.go
- kubernetes/api/v1alpha1/servicelevelobjective_types_test.go
- kubernetes/controllers/servicelevelobjective_test.go
- slo/rules.go
- slo/slo.go
This MR propagates all lables prefixed with 'pyrra.dev/' to  the generated
rule groups, while stripping said prefix in the final label. This is so we can
still yaml.Marshal the RuleGroup and receive a label that complies with the
Prometheus data model.
It also adds some whitespace changes in the test files to make it easier for IDEs
to collapse individual tests.
Closes #157
> Propagate k8s labels prefixed with pyrra.dev/ to RuleGroup

- filesystem.go
- openapi/server.go
- slo/slo.go
- ui/src/pages/Detail.scss
- ui/src/pages/Detail.tsx
- ui/src/pages/List.scss
- ui/src/pages/List.tsx
First of all we strip `pyrra.dev/` from the labels now before they get send to the UI via the API.
This gets rid of the issue in #289. 
Second, we then need  to fix the matching of objectives to match for both `team=thanos` and `pyrra.dev/team=thanos`. If both don't exist we exclude the objective from the returned list.
Third, the UI and backend needed to support grouping labels, like `handler=/api/v1/query` that's not in the label set of the objective but actually comes from Prometheus. Pyrra now checks if a grouping label, like `handler` for example, is part of the objective's groupings.
Fixes #289
> Fix label and grouping matching both in backend and UI

- main.go
I can be useful to support basic auth as not all prometheus support bearer token.
This PR add its support by using `promconfig.BasicAuth`
> Add support for basic auth against Promtheus

- main.go
If `NaN` is tried to be marshalled to JSON it'll fail and the returned response will simply be empty...
> Fix multi burn rate alerts current value NaN handling

- main.go
- main_test.go
- slo/promql.go
- slo/promql_test.go
- slo/rules.go
- slo/rules_test.go
- ui/src/pages/List.tsx
Currently the fix for release-0.4 was to use a raw query.
However, we already use those queries in the recording rules that are used by the alerting itself. 
This PR improves the implementation to query the exact same recording rules for the UI too.
> Use burnrate recording rules to query for alerts table

- slo/promql.go
Since it's a map to pointers it's possible that the underlying matcher gets concurrently accessed and rewritten. Copying the labels avoids this problem.
The symptom of how this showed up was that sometimes the metric and the label `__name__` were different and Prometheus returned an error.
> slo: Copy labels for burnrate queries to avoid possible race

- ui/src/pages/List.scss
- ui/src/pages/List.tsx
The filter badges still work though since they stop propagating the click event now.
Thanks for pointing out @lilic! 🎉
> ui: Entire row in List.tsx is clickable again

- main.go
This one I was chasing for weeks now. It turns out that Pyrra often show's "No Data" because the timestamp send to Prometheus is actually too far in the future (at 15:01 it rounds to 15:05) and Prometheus doesn't yet have data.
This was an optimization for when the availability & error budget weren't recording rules yet.
Turns out 5min was way too much anyway...
Hopefully the "no data" is mostly a thing of the past now.
> Don't round objective status query time

- examples/nginx.yaml
It's not part of the ServiceLevelObjective spec.
> Remove `spec.latency` from nginx.yaml example

- kubernetes/api/v1alpha1/servicelevelobjective_types.go
- kubernetes/api/v1alpha1/servicelevelobjective_types_test.go
- kubernetes/controllers/servicelevelobjective_test.go
- slo/rules.go
- slo/slo.go
Re-using the same strategy used to propagate labels from SLO definitions to alerts, this propagates annotations from SLO to alerts. If any annotation is prefixed with `pyrra.dev/`, then this annotation will be present in the alert while the prefix itself is removed.
PS: Differently from the labels propagation, annotations are only propagated to alerting rules and not to recording rules.
---
Should fix https://github.com/pyrra-dev/pyrra/issues/112
> Propagate annotations from SLO to alerts

- examples/grafana/detail.json
- examples/grafana/list.json
The first dashboard is a table of all SLOs and their state. By clicking on the name of a SLO you can drill down into the specific SLO to open the detail dashboard. 
The detail dashboard shows the error budget over time and also shows the Rate and Errors of the underlying SLI. 
_The gaps in the screenshot exist due to running this in a Kubernetes cluster on a MacBook. There usually are no gaps._
_Note: For this feature the backend for filesystem or kubernetes needs to be run with `--generic-rules` enabled._
> Create Grafana dashboards

- Dockerfile
AppArmor on GKE clusters will block simply running as nobody and wants a specific user number. https://kubernetes.io/docs/tutorials/security/apparmor/
> Set USER to 65533

- ui/src/components/Navbar.scss
- ui/src/components/Navbar.tsx
- ui/src/index.scss
- ui/src/index.tsx
- ui/src/pages/Detail.scss
- ui/src/pages/Detail.tsx
Next to improving the style for the metric tiles, like font and text, we add new xxxl and xxxxl breakpoints to improve the width of Pyrra on big screens. This allows to show the metric graphs for Requests, Errors and Duration next to each other on big screens.
Old:
New:
Additionally, I've created new larger containers so that Pyrra get get wider on bigger screens, allowing the list to be better readable if it has many labels, as well as, having enough screen width to actually put the RED graphs next to each other on big enough screens:
List old:
List new
RED old:
RED new:
It's probably best to look at this on the deployed version on https://demo.pyrra.dev
> ui: Improve styles for metric tiles and add large breakpoints

- ui/src/components/graphs/DurationGraph.tsx
- ui/src/pages/Detail.tsx
As discussed in https://github.com/pyrra-dev/pyrra/pull/450#issuecomment-1272354942 we would have much preferred the latency target to be shown as separate series too. Including a legend. 
Well, here it is. You can also disable it being shown by clicking on the legend.
> UI: Add latency target as own series

- kubernetes/controllers/servicelevelobjective_test.go
- slo/rules.go
- slo/rules_test.go
If a metric for a SLO and SLI isn't available, called absent, we will fire an alert pretty quickly. It also should be of severity critical as we aren't able to tell if the error budget is burning too quickly. Hence, we'll treat it like the worst outage for the service possible.
related to #448 
cc @ArthurSens 
Maybe interesting for you too @brancz @paulfantom
> slo: Create absent rules for SLI metrics

- ui/src/App.tsx
- ui/src/components/graphs/DurationGraph.tsx
Additionally, support setting the precision in formatDuration to not return 3 time durations.
Fixes #478
> ui: Support microseconds and nanoseconds

- ui/src/components/graphs/RequestsGraph.tsx
Seems like this was indeed a bug. All other graphs already use `toFixed`. 
Closes #534
> ui/src/components: Use toFixed in RequestsGraph

- filesystem.go
- generate.go
- main.go
Fixes #314 
Just took a quick try into 314... Fixes the issue but I basically copied code from `filesystem.go`, so I believe the code can still be improved to reduce duplicated code😅
Opening the PR early just in case you were imagining something different here 🙂
> Add generate command

- slo/promql.go
- slo/promql_test.go
This pull request fixes a bug in the use of the `slices.Clone` function in the slo/promql.go file.
The `slices.Clone` method is not suitable for cloning the label matchers, which is a list of pointers. This is because the `slices.Clone` method only copies the same pointers, instead of creating new values.
I implemented a new function called `cloneMatchers`, which creates new values instead of copying pointers. The `cloneMatchers` function is used in place of the `slices.Clone` method in several parts of the code where the label matchers are being cloned.
> Fix label matchers mutability

- slo/promql.go
This pull request enhances the functionality of the replacer by introducing support for replacing the scalar value of 86400 with the duration of the window. The scalar value of 86400 represents the number of seconds in one day, making it an easily recognizable constant.
> Replacer: Add support for replacing duration in seconds

- ui/src/components/graphs/aligneddata.tsx
Support for graph data that not only has multiple or no labels.
Previously, the graph would not display any data that had no labels, and in cases where the data had multiple labels, there was a potential for the labels to be incorrectly attached to wrong time series in the graph. However, it is unclear if the multi-labels scenario actually occurs in practice.
> ui/aligneddata: support for no label and multiple labels

- slo/rules.go
- slo/rules_test.go
The PR fixes #612 
In addition, I renamed `errors` variables, because they collide with golang `errors` package which is also imported
> Use errors metric name in availability generic rule 

- slo/rules.go
- slo/rules_test.go
Fixes generic recording rules for SLOs with different metric names. 
Fix is originally from @m-messiah #613 🙏
> Fix ratio generic recording rules for SLOs with different metric names

- ui/src/components/graphs/DurationGraph.tsx
- ui/src/components/graphs/ErrorBudgetGraph.tsx
- ui/src/components/graphs/ErrorsGraph.tsx
- ui/src/components/graphs/RequestsGraph.tsx
- ui/src/components/graphs/selectTimeRange.tsx
- ui/src/pages/Detail.tsx
Using text like `now` and `now-12h` will not spam the browser's history like reported in #590.
However, selecting a specific time range with the cursor in the graphs will now still select the very specific timestamps and store them in the URL.
> Use text for relative timestamps and numbers for absolute

- main.go
- ui/src/App.tsx
- ui/src/components/AlertsTable.tsx
- ui/src/components/graphs/DurationGraph.tsx
- ui/src/components/graphs/ErrorBudgetGraph.tsx
- ui/src/components/graphs/ErrorsGraph.tsx
- ui/src/components/graphs/RequestsGraph.tsx
- ui/src/duration.tsx
- ui/src/pages/Detail.tsx
- ui/src/pages/List.tsx
- ui/src/prometheus.spec.tsx
- ui/src/prometheus.tsx
The new approach of sending the queries along with the objective has the drawback of hardcoding the interval. This will now use `1s` window intervals and replace them in the string with the actually wanted interval windows - what previously had been done on the backend.
> ui: Replace interval in queries - refactor duration

- filesystem.go
- generate.go
- main.go
This PR adds a `--operator-rule` flag to the `generate` command, allowing users to generate their Pyrra SLO recording/alerting rules in `monitoringv1.PrometheusRule` format.
> Add --operator-rule flag to generate cmd

- ui/src/components/graphs/ErrorBudgetGraph.tsx
This was a super long-standing bug...
The fix is to not calculate the zero height's percentage relative to the entire canvas but to create the gradient relative to the min and max y-values. This makes the entire math easier and correct.
Fixes #57
> ui: Fix the ErrorBudgetGraph's gradient

- ui/src/components/graphs/gaps.tsx
Computing the gaps needs to not only look at timestamps now but also whether or not the values are `null` since merging #615
> ui/src/components/graphs: Gaps take nulls into account now

- .gitignore
- CONTRIBUTING.md
- kubernetes.go
- main.go
This PR adds graceful termination to the api command and performs a small refactor of graceful termination in the kubernetes command.
Additionally, the first two commits are maintenance: updates to gitignore and the contributing document.
> api/kubernetes: handle graceful termination

- main.go
The panic happened because within the latency objective we referenced the ratio...
Fixes #666 
I guess we should really look into having interfaces for these things... :grimacing:
> Fix panic in ErrorBudgetGraph

- ui/src/components/AlertsTable.scss
- ui/src/components/AlertsTable.tsx
- ui/src/components/Icons.tsx
- ui/src/components/graphs/BurnrateGraph.scss
- ui/src/components/graphs/BurnrateGraph.tsx
- ui/src/components/graphs/DurationGraph.tsx
- ui/src/components/graphs/ErrorsGraph.tsx
- ui/src/components/graphs/RequestsGraph.tsx
- ui/src/components/graphs/aligneddata.spec.tsx
- ui/src/components/graphs/aligneddata.tsx
- ui/src/components/graphs/colors.tsx
- ui/src/index.scss
- ui/src/labels.tsx
- ui/src/pages/Detail.tsx
Every multi burn rate alert now has a graph showing the short and long burn rate. It shows the threshold both burn rates have to be above for the alert to start firing (first pending). Once pending or firing the background of the graph changes color depending on the alert's state.
Firing or pending burn rates will automatically show the graph expanded in the table.
> Add burnrate graphs to multi burn rate alerts table

- slo/promql.go
- slo/rules.go
- slo/slo.go
This should drastically improve the ergonomics of dealing with the different indicator types. We should do similar things for the individual fields inside the indicators.
> Create`objective.IndicatorType()` and use switch-cases

- slo/rules.go
- slo/rules_test.go
This issue was uncovered after activating the generation of generic rules, one error budget in particular was extremely low on Grafana but all OK according to pyrra / manual checks.
We have 2 SLOs setup for one of our application:
```yaml
indicator:
ratio:
errors:
metric: grpc_server_processing_duration_seconds_count{app_kubernetes_io_name="grpc_server", statusCode!="OK"}
total:
metric: grpc_server_processing_duration_seconds_count{app_kubernetes_io_name="grpc_server"}
target: "99"
window: 2w
```
And a second one:
```yaml
indicator:
latency:
success:
metric: grpc_server_processing_duration_seconds_bucket{app_kubernetes_io_name="grpc_server", le="0.1"}
total:
metric: grpc_server_processing_duration_seconds_count{app_kubernetes_io_name="grpc_server"}
target: "95"
window: 2w
```
Both rules …
> Fix: Matcher label of generic rules for Ratio SLOs

- slo/promql.go
- slo/promql_test.go
We summed up the total and errors instead of querying for only the total by matching `le=""`. This is fixed now and the error budget graph and card have the same values again.
Closes #697
> slo: Fix total query for latency

- slo/rules.go
Closes #727
Use the o.commonRuleLabels method when generating the generic rules which allows for specifying custom labels.
> feat: propgate custom labels to generic rules

- filesystem.go
- filesystem_test.go
- main.go
I changed the test in `filesystem_test.go` because my IDE was complaining about the variable shadowing between [here](https://github.com/pyrra-dev/pyrra/blob/dfc8e4b819309fc0e132795cbf760d879063a1c3/kubernetes_test.go#L21) and [here](https://github.com/pyrra-dev/pyrra/blob/dfc8e4b819309fc0e132795cbf760d879063a1c3/filesystem_test.go#LL13C3-L13C3)
I guess there are two ways of solving this? I think using the regex approach suggested in the issue we would have to not use `filepath.Glob` anymore?
I felt this approach was slightly easier and wouldn't technically break anyone by changing the behaviour of the `--config-files` flag.
Should we accept `.yaml` or `.yml`? 
fixes #726
> fix(filesystem): only watch for files with the .yaml extension

- logger.go
- logger_test.go
- main.go
Added two new global command line flags to the pyrra binary.
```
--log-level="info"       Used to set the logging level of the application. Valid options are 'debug', 'info', 'warn' or 'error'
--log-format="logfmt"    Used to set the logging format. Valid options are 'logfmt' or 'json'
```
We also validate these options with the level.Parse function from go-kit itself and some custom validation about the two options for logging formats.
<details>
<summary>View Manual Test Cases</summary>
```bash
pyrra git:(feat/configurable-logger/769) ✗ go run . api --log-level=ciccio
pyrra: error: pyrra: invalid level string: must be 'debug', 'info', 'warn' or 'error'
exit status 1
pyrra git:(feat/configurable-logger/769) ✗ go run . api --log-level=debug 
level=info ts=2023-06-14T20:50:32.933428291Z …
```
> feat: adding --log-format and --log-level as global flags

- filesystem.go
Pyrra's filesystem component is now going to validate the given config file. If there is an error it will be returned and logged. Nothing will be done with that file. If there are warnings, the warnings will be logged, but the Prometheus rules are generated.
These metrics are increased and can be alerted on too:
```
pyrra_filesystem_reconciles_errors_total 7
pyrra_filesystem_reconciles_total 23
```
> filesystem: First validate objectives

- config/crd/bases/pyrra.dev_servicelevelobjectives.json
- config/crd/bases/pyrra.dev_servicelevelobjectives.yaml
- kubernetes/api/v1alpha1/servicelevelobjective_types.go
- kubernetes/controllers/servicelevelobjective.go
So far running `kubectl get slo` would only show something similar to this:
```
NAMESPACE    NAME                                                      AGE
monitoring   servicelevelobjective.pyrra.dev/pyrra-filesystem-errors   18h
monitoring   servicelevelobjective.pyrra.dev/thanos-query              18h
```
With these changes the status contains the resource type that was generated. Either `PrometheusRule` or `ConfigMap`. Additionally, some fields from the spec are extracted and shown in the output too:
`kubectl get slo,prometheusrule`
```
NAMESPACE    NAME                                                      WINDOW   TARGET   TYPE            AGE
monitoring   servicelevelobjective.pyrra.dev/pyrra-filesystem-errors   1w       99       PrometheusRule  18h
monitoring …
```
> Kubernetes: Update SLO resource's status

- kubernetes/api/v1alpha1/servicelevelobjective_types.go
- kubernetes/api/v1alpha1/servicelevelobjective_types_test.go
Add more validation.
This time for `latencyNative` indicators.
> kubernetes/api: Add validation for latencyNative indicators

- kubernetes.go
One last accidential fix by dependabot.
While I required CI checks to pass I didn't provide the list of which ones. Weird UX there.
> Fix metricsserver options

- ui/src/components/Icons.tsx
- ui/src/components/graphs/ErrorBudgetGraph.tsx
- ui/src/components/graphs/ErrorsGraph.tsx
- ui/src/pages/Detail.scss
- ui/src/pages/Detail.tsx
By default, they are now absolute, but if some graph looks too flat they can be made relative.
cc @paulfantom
Closes #540
_Notice the `0%`at the bottom left in the graph_
_Notice the `7.90%`at the bottom left in the graph_
> ui: Add option to make graphs absolute or relative

- .github/workflows/generate.yaml
This commit adds a workflow for generated files with a job to check
Jsonnet in the examples/ directory. I tested this locally with act and
correctly got a diff and a failure when bumping the Pyrra version in
examples/openshift.main.jsonnet.
Fixes: https://github.com/pyrra-dev/pyrra/issues/934
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>
> CI: add job to check Jsonnet

- README.md
> Fix dir name in URL in README.md

- kubernetes/controllers/servicelevelobjective.go
Fixes #992 
There was an else missing after checking if err != not found in the prometheusRule/configMap reconciliation loop.
Additionally, I'm standardizing the error messages between PrometheusRule and ConfigMap errors
> Fix Reconciliation errors when PromRule/ConfigMap doesn't exist

- filesystem.go
- jsonnet/pyrra/kubernetes.libsonnet
- kubernetes.go
- main.go
This adds a configuration option for the `prometheus-url` parameter to the API server, making it easier to point the server at thanos-query or a differently named Prometheus instance.
> jsonnet/pyrra: Add prometheusURL configuration option

- slo/promql_test.go
- slo/rules.go
- slo/rules_test.go
Same as #327
Ratio SLOs were the only ones creating these "grouping" on regexp filters
Fixes #1050
> slo: fix ratio burnrate recording rules with regexp matchers

- examples/grafana/detail.json
This panel actually shows the rate of errors occurring but is configured to display this as percentunit. This results in it showing a 200% error rate when there are actually 2 errors occurring per second. Change the unit for this panel to reqps instead.
> Fix the display of the "Errors" panel in the SLO detail dashboard

- ui/src/components/graphs/RequestsGraph.tsx
- ui/src/pages/Detail.tsx
For some reason the requests graph slipped and only ever showed the (previously default) relative data.
Now, when toggling between absolute and relative data, the requests graphs changes accordingly.
> ui: RequestsGraph shows absolute and relative data

- examples/kubernetes/README.md
Update commands in [readme file](https://github.com/pyrra-dev/pyrra/blob/main/examples/kubernetes/README.md) with the right paths.
Fixes [#1159](https://github.com/pyrra-dev/pyrra/issues/1159)
> Fix typo in k8s example readme

- kubernetes/api/v1alpha1/servicelevelobjective_types.go
- kubernetes/api/v1alpha1/servicelevelobjective_types_test.go
Even if a vector expression in an SLO returns a vector, the webhook API
handler will panic if the underlying expression is not a vector selctor.
Fixes: https://github.com/pyrra-dev/pyrra/issues/1181
Signed-off-by: squat <lserven@gmail.com>
> webhook: fix panic on unedpected parser expression

- kubernetes/api/v1alpha1/servicelevelobjective_types.go
- kubernetes/api/v1alpha1/servicelevelobjective_types_test.go
Even if a vector expression in an SLO returns a vector, the webhook API
handler will panic if the underlying expression is not a vector selctor.
Fixes: https://github.com/pyrra-dev/pyrra/issues/1181
Signed-off-by: squat <lserven@gmail.com>
> webhook: fix panic on unexpected parser expression

- .errcheck_excludes.txt
- .golangci.yml
Some of these were deprecated and printed warnings.
> Update the golangci lint config

- kubernetes/api/v1alpha1/servicelevelobjective_types.go
- kubernetes/api/v1alpha1/servicelevelobjective_types_test.go
- main.go
This gets rid of a "bug" where having `0.9990000000000001` instead of `0.999`.
Fixes #1197
> Round target to 5 decimal points

- examples/grafana/detail.json
- examples/grafana/list.json
The PR updates the dashboards to Grafana 10.X. Additionally the datasource variable was renamed to have the same naming as for https://github.com/prometheus-operator/kube-prometheus/tree/main/manifests
> fix(examples,grafana): correct dashboards for Grafana 10.X

- examples/kubernetes/manifests-webhook/slos/slo-apiserver-read-cluster-latency.yaml
- examples/kubernetes/manifests-webhook/slos/slo-apiserver-read-namespace-latency.yaml
- examples/kubernetes/manifests-webhook/slos/slo-apiserver-read-resource-latency.yaml
- examples/kubernetes/manifests/slos/slo-apiserver-read-cluster-latency.yaml
- examples/kubernetes/manifests/slos/slo-apiserver-read-namespace-latency.yaml
- examples/kubernetes/manifests/slos/slo-apiserver-read-resource-latency.yaml
- examples/openshift/manifests/slos/slo-apiserver-read-cluster-latency.yaml
- examples/openshift/manifests/slos/slo-apiserver-read-namespace-latency.yaml
- examples/openshift/manifests/slos/slo-apiserver-read-resource-latency.yaml
- jsonnet/pyrra/kubernetes.libsonnet
Since the k8s-mixin is moved to [using the SLI.* metrics](https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/874/files), can we change the default SLOs to use the SLI.* metrics? Is it set/pinned to support older k8s versions (https://github.com/pyrra-dev/pyrra/pull/915/commits/12e7e5eab303b1707a5af1ad580109e95fe45918)?
> fix(slos): Use apiserver_request_sli.* metrics

- slo/rules.go
- slo/rules_test.go
While trying to use [Azure Prometheus Rules Converter](https://github.com/Azure/prometheus-collector/tree/main/tools/az-prom-rules-converter#az-prom-rules-converter) with generic rules enabled, the following error was thrown:
```
Failed to validate Prometheus Rules Schema
[
{
"instancePath": "/groups/2/rules/1/expr",
"schemaPath": "#/properties/expr/type",
"keyword": "type",
"params": {
"type": "string"
},
"message": "must be string"
},
]
```
This corresponds to the `pyrra_window` expression, which is currently a raw integer. Turning it into a string fixes the issue and does not seem to have any impact on the rule on Prometheus. This is also in line with the fact that `pyrra_objective` is also stringified.
> fix: stringify pyrra_window expression

- examples/docker-compose/docker-compose.yaml
- Enable lifecycle API to reload.
- Change running user to be able to write to share volume.
```
level=info ts=2024-07-12T10:15:32.058814841Z caller=main.go:142 msg="using Prometheus" url=http://prometheus:9090
level=info ts=2024-07-12T10:15:32.058882208Z caller=filesystem.go:131 msg="watching directory for changes" directory=/etc/pyrra
level=info ts=2024-07-12T10:15:32.059549038Z caller=filesystem.go:261 msg="starting up HTTP API" address=:9444
level=error ts=2024-07-12T10:15:32.064182232Z caller=filesystem.go:185 msg="error creating rule file" file=/etc/pyrra/prometheus-http.yaml err="failed to write file \"/etc/prometheus/pyrra/prometheus-http.yaml\": open /etc/prometheus/pyrra/prometheus-http.yaml: permission denied"
level=warn ts=2024-07-12T10:15:37.073472514Z …
```
> fix(docker-compose): minor changes

- kubernetes/controllers/servicelevelobjective_test.go
- slo/rules.go
- slo/rules_test.go
- slo/slo.go
This PR introduces the AbsentDuration method.
AbsentDuration calculates the duration when absent alerts should fire. The idea is as follows:
Use the most critical of the multi burn rate alerts. For that alert to fire, both the short AND long windows have to be above the threshold. The long window takes the - longest - to fire. Assuming absence of the metric means 100% error rate, the time it takes to fire is the duration for the long window to go above the threshold `(factor * objective)`. Finally, we add the "for" duration we add to the multi burn rate alerts.
Taking the windows and the objective into account the absent alert depends on your SLO's objective and window.
Looking at the tests the duration significantly increased for most absent alerts.
> Improve Absent alert duration

- main.go
We explicitly check for existence in status before adding this metric, but then we reference the status we know we didn't retrieve. I think the broader bug might be that the fingerprints for the total value is different than the one for the errors, so we might need to collate by closest objective label or something, but this should fix the Nil pointer exceptions.
fixes #1393
> Fix nil pointer reference in GetStatus()

- examples/kubernetes/manifests-webhook/slos/slo-apiserver-read-cluster-latency.yaml
- examples/kubernetes/manifests-webhook/slos/slo-apiserver-read-namespace-latency.yaml
- examples/kubernetes/manifests/slos/slo-apiserver-read-cluster-latency.yaml
- examples/kubernetes/manifests/slos/slo-apiserver-read-namespace-latency.yaml
- examples/openshift/manifests/slos/slo-apiserver-read-cluster-latency.yaml
- examples/openshift/manifests/slos/slo-apiserver-read-namespace-latency.yaml
- jsonnet/pyrra/kubernetes.libsonnet
https://github.com/prometheus-operator/kube-prometheus/commit/69d9636b64192418d64912c032f5437361e88ea5 dropped the "5" bucket.
> fix(SLOs): Use the 5.0 bucket by default

- .github/dependabot.yml
We want to keep updating the latest release branch with patch fixes. This will hopefully get Dependabot to do that.
> Update Dependabot config to patch update release branches

- slo/promql.go
- slo/promql_test.go
A histogram can be created with no data in (for example, an application might have a 5xx series with no data in, so that increases can be caluclated). Using `histogram_fraction` against series that contains NaN results in NaN, even if other series exist. However, if we sum before histogram_fraction, then the NaNs are essentially ignored.
> Support empty histogram series

- examples/grafana/README.md
- examples/grafana/detail.json
- slo/promql.go
- slo/rules.go
- slo/rules_test.go
Simplest, but not necessarily the best way to fix #968 968
> chore: fix missleading errors total grafana

- ui/src/pages/List.tsx
This PR fixes the display of invalid SLOs in the List view. When the filesystem component encounters an error for an SLO configuration, it returns `{window: "0s", queries: {}}`. Previously, this would display an almost empty row in the table.
- Added error detection in the List component to check for `window.seconds === 0`
- Display "Error: Invalid SLO configuration" in red text when this condition is detected
- Disabled row click navigation for invalid SLOs to prevent navigating to a broken detail page
1. Create an invalid SLO configuration that causes the filesystem component to return an error
2. View the objectives list page
3. Verify that the invalid SLO shows "Error: Invalid SLO configuration" in the Window column
4. Verify that clicking on the invalid SLO row does not navigate to …
> fix: display error message for invalid SLOs with window=0s

- main.go
I want to add support for multi-tenant Mimir in the read path. The goal is to be able to have a single Pyrra instance query SLOs from multiple tenants in a Mimir instance. This does not include generating rules and pushing them to the Mimir tenants as that would involve adding multi-tenancy support to Pyrra itself.
The use case for this is running Pyrra in a CI pipeline generating the rule files and pushing the rules through the Mimir CLI. These rules get pushed to different tenants, but then the Pyrra UI should be able to query the SLO for all the tenants. This is achieved by providing multiple tenants in the `X-Scope-OrgID` header. A single tenant can also be set through this flag.
The Mimir [documentation](https://grafana.com/docs/mimir/latest/manage/secure/authentication-and-authorizat …
> feat: support querying data from multiple Mimir tenants
