- config/api.cue
- config/api.yaml
- config/kubernetes.cue
- config/kubernetes.yaml
Signed-off-by: yeya24 <yb532204897@gmail.com>
The deployment files need to be updated due to changes in https://github.com/pyrra-dev/pyrra/pull/17
> update deploy flags in config

- examples/nginx.yaml
- examples/prometheus-http.yaml
- examples/prometheus-operator.yaml
- examples/thanos-grpc.yaml
- examples/thanos-http.yaml
Finally got around to update the examples.
Closes #20
> Fix examples

- config/crd/bases/pyrra.dev_servicelevelobjectives.yaml
- examples/kubernetes/README.md
- examples/kubernetes/slos/apiserver-request-errors.yaml
- examples/kubernetes/slos/apiserver-request-latency.yaml
- examples/kubernetes/slos/coredns-request-latency.yaml
- examples/kubernetes/slos/coredns-response-errors.yaml
- examples/kubernetes/slos/prometheus-http-errors.yaml
As discussed during the livestream earlier, here's the Kubernetes demo that I've started, @solidnerd.
> Create a Kubernetes demo based on kube-prometheus

- ui/src/components/graphs/ErrorBudgetGraph.tsx
- ui/src/components/graphs/ErrorsGraph.tsx
- ui/src/components/graphs/RequestsGraph.tsx
> ui: Increase graph left padding for y axis numbers

- ui/public/index.html
- ui/src/components/AlertsTable.tsx
- ui/src/components/Navbar.scss
- ui/src/components/Navbar.tsx
- ui/src/components/graphs/ErrorBudgetGraph.tsx
- ui/src/pages/Detail.scss
- ui/src/pages/Detail.tsx
- ui/src/pages/List.tsx
When improving the UI right before the launch, we somewhat ignored responsive layouts for a bit.
This PR fixes the left over parts of Pyrra.
Closes #3
> Make Pyrra responsive again

- examples/pyrra-filesystem-errors.yaml
- examples/pyrra-http-errors.yaml
- examples/pyrra-kubernetes-errors.yaml
- filesystem.go
- main.go
- openapi/server.go
Additionally, we add some example SLOs for Pyrra itself :slightly_smiling_face:  
Closes #16
> Add metrics to API and filesystem components

- CHANGELOG.md
- README.md
- config/api.yaml
- config/kubernetes.yaml
- examples/docker-compose/docker-compose.yaml
Merge the changes for v0.1.0 back into main
> Merge release-0.1 back into main

- main.go
- ui/package.json
- ui/public/index.html
- ui/src/App.tsx
- ui/src/components/AlertsTable.tsx
- ui/src/components/graphs/gaps.tsx
- ui/src/index.tsx
- ui/src/pages/Detail.tsx
- ui/src/pages/List.tsx
This adds support for running Pyrra behind proxies like an oauth proxy.
Closes #49
> Add support for route prefix like / and /pyrra

- main.go
Sometimes (especially when new SLOs were created) we cached empty responses and then had to wait up to 5min or 10min to get the actual  data once the recording rules were firstly evaluated.
With this patch we'll only start caching when there's meaningful content returned.
> Only cache responses when they had content

- slo/promql.go
- slo/promql_test.go
Seems I got a bit ahead of myself removing the grouping during the refactoring and thus breaking the grouping feature altogether...
> slo: Fix PromQL grouping

- README.md
> Extend docs with 'How It Works' section

- filesystem.go
- kubernetes.go
- kubernetes/controllers/servicelevelobjective.go
- main.go
> Wrap errors with more context

- main.go
Users should see fewer requests simply fail in the UI when many are send concurrently.
> Use the Prometheus HTTP round tripper with better defaults

- filesystem.go
- main.go
The timeout is pretty important as reloading Prometheus is rather expensive. It may happen that Pyrra generates a couple of files in a short period of time (like at startup) and we want to make sure to wait for a brief moment until we're mostly done and only then reload Prometheus.
> filesystem: Trigger Prometheus reload if files changed after timeout

- ui/src/pages/List.scss
- ui/src/pages/List.tsx
Update the styles of the row for SLOs with firing alerts:
> ui: Highlight entire row for SLO with firing alerts

- ui/src/components/AlertsTable.tsx
- ui/src/components/graphs/ErrorBudgetGraph.tsx
- ui/src/components/graphs/ErrorsGraph.tsx
- ui/src/components/graphs/RequestsGraph.tsx
- ui/src/labels.tsx
- ui/src/pages/List.tsx
I'm tired of typing `{ [key: string]: string }` every time.
> ui: Create a Labels type and use it throughout

- ui/src/index.scss
- ui/src/labels.tsx
- ui/src/pages/List.scss
- ui/src/pages/List.tsx
> Add filtering to the list page

- main.go
> Check on metric existence when calling objective status

- ui/src/index.tsx
Creation of ReactDOM needs to be updated for all React 18 features.
> Fix React 18 DOM createRoot

- main.go
> Use correct Prometheus URL in filesystem sub command

- ui/.prettierrc
- ui/src/App.tsx
- ui/src/components/AlertsTable.tsx
- ui/src/components/Icons.tsx
- ui/src/components/Navbar.tsx
- ui/src/components/graphs/ErrorBudgetGraph.tsx
- ui/src/components/graphs/ErrorsGraph.tsx
- ui/src/components/graphs/RequestsGraph.tsx
- ui/src/components/graphs/colors.tsx
- ui/src/components/graphs/gaps.tsx
- ui/src/index.scss
- ui/src/index.tsx
- ui/src/labels.tsx
- ui/src/pages/Detail.scss
- ui/src/pages/Detail.tsx
- ui/src/pages/List.scss
- ui/src/pages/List.tsx
- ui/src/setupTests.ts
- ui/tsconfig.json
Running `prettier -w .` inside the `/ui` folder.
> ui: Format all files using prettier

- ui/src/components/graphs/RequestsGraph.tsx
Usecase this pull-request is meant to solve: https://github.com/pyrra-dev/pyrra/issues/384
> Added regex case for statuscodes that contain digits and letters.

- ui/src/App.tsx
- ui/src/components/graphs/ErrorsGraph.tsx
- ui/src/pages/Detail.tsx
- ui/src/pages/List.tsx
It's not perfect...
Closes #58
> ui: Improve UI for displaying latency objectives

- ui/src/components/graphs/ErrorBudgetGraph.tsx
- ui/src/components/graphs/ErrorsGraph.tsx
- ui/src/components/graphs/RequestsGraph.tsx
This is mostly value formatting improvements for the graphs.
> ui: Improve existing graphs value formatting

- ui/src/components/graphs/RequestsGraph.tsx
> Match labels as lower case for colors

- examples/kubernetes/README.md
enhance the doc for kubernetes example
Signed-off-by: Ziqi Zhao <zhaoziqi9146@gmail.com>
> enhance the doc for kubernetes example

- filesystem.go
- go.mod
- go.sum
- main.go
Next the upstream project should support histograms and we'd have feature parity for the most important parts. 
Closes #529
> Use polarsignals/connect-go-prometheus interceptor

- examples/docker-compose/docker-compose.yaml
Signed-off-by: songjiayang <songjiayang1@gmail.com>
Changes for: 
- Ensure Prometheus's prometheus_pyrra volume is same as pyrra-filesystem.
- pyrra-filesystem can reload Prometheus after some rules generated.
> update docker-compose example

- .github/workflows/container.yaml
> CI: Don't push images on pull requests

- main.go
> Log errorful queries

- filesystem.go
> Filesystem: log errors

- ui/src/components/graphs/aligneddata.spec.tsx
- ui/src/components/graphs/aligneddata.tsx
> Handle missing samples in convertAlignedData with multiple series correctly

- kubernetes.go
- main.go
Thanks, @asubiotto, I've cherry-picked your commits for a patch release of v0.5.x.
> `release-0.5`: handle graceful termination

- ui/src/App.tsx
- ui/src/pages/Detail.tsx
- ui/src/pages/List.tsx
This will make it drastically easier for local development. No more need to update the index.html every time :smiley:
> ui: Fallback to local dev URLs if API_BASEPATH undefined

- ui/src/components/AlertsTable.tsx
- ui/src/components/graphs/BurnrateGraph.tsx
- ui/src/pages/Detail.tsx
For some reason I thought they might be better formatted as percentages which in hindsight is incorrect. So this commit reverts back to using the plane numbers.
> Revert using percentage for burn rates

- kubernetes.go
> kubernetes: Start kubernetes controller manager

- kubernetes/controllers/servicelevelobjective.go
**Description:**
Delete useless conditionals to improve quality of code
> fix: remove useless conditionals

- examples/grafana/README.md
Changes:
- Added additional information on generic-rules to make the Grafana dashboards work.
- Lint changes, mostly deletion of `^M`
> doc: additional information on generic-rules

- config/crd/bases/pyrra.dev_servicelevelobjectives.json
- config/crd/bases/pyrra.dev_servicelevelobjectives.yaml
- kubernetes/api/v1alpha1/servicelevelobjective_types.go
Changes:
- some typos and missing words in CRDs
> fix: typos and doc fixes in crds

- main.go
> Pass basic auth flags for both API and Filesystem commands

- kubernetes/api/v1alpha1/servicelevelobjective_types.go
- kubernetes/api/v1alpha1/servicelevelobjective_types_test.go
Add validation errors and warnings for latency indicators if found.
> kubernetes/api: Add validation for latency indicators

- .github/workflows/dependabot-merge.yaml
It's kind of time consuming to go through 15 PRs each week. 
Just merge them if they are green.
> Auto merge successful dependabot PRs

- ui/package-lock.json
- ui/package.json
- ui/src/components/Icons.tsx
- ui/src/index.scss
- ui/src/pages/List.scss
- ui/src/pages/List.tsx
The big table on the list page now uses [react-table](https://tanstack.com/table/v8). 
This library is amazing as it takes care of so many things one would need to implement manually, like sorting, filtering, column visibility, formatting, and more. 
Additionally, a search input has been added. It searches for SLO names and also works to search for label name and values. 🎉
> Refactor List table to use react-table

- kubernetes/api/v1alpha1/servicelevelobjective_types.go
- kubernetes/api/v1alpha1/servicelevelobjective_types_test.go
Validation for the final missing indicator.
> Add validation for BoolGauge indicators

- ui/src/pages/List.tsx
This was still missing from the table refactoring.
Warning on the availability column if the total column is hidden.
Warning on the total column instead whenever it's visible.
> ui: Show tooltip with volume warning again

- ui/src/pages/Detail.scss
- ui/src/pages/Detail.tsx
This greatly improves the UX for absolute or relative scaling.
Ideas by @nadinevehling
> ui: Improve the scale buttons on the detail page
